services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  app:
    image: allotment-node
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
